theme: jekyll-theme-cayman
title: Welcome :]
description: ＼＼\\٩( 'ω' )و //／／
url: SakurajimaMai02.github.io
timezone: Asia/Beijing
encoding: "utf-8"
repository: SakurajimaMai02/Sakurajima02.github.io
location: China
author: SakurajimaMai02
